[package]
name = "retworkx"
description = "A python graph library implemented in Rust"
version = "0.4.0"
authors = ["Matthew Treinish <mtreinish@kortar.org>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/Qiskit/retworkx"
keywords = ["python", "graph"]

[badges]
travis-ci = {repository = "Qiskit/retworkx"}

[lib]
name = "retworkx"
crate-type = ["cdylib"]

[dependencies]
petgraph = "0.5.1"
fixedbitset = "0.2.0"
hashbrown = "0.8"
numpy = "0.11.0"
ndarray = "0.14.0"
rand = "0.7"
rand_pcg = "0.2"

[dependencies.pyo3]
version = "0.11.1"
features = ["extension-module"]
